name: Flag Service CD

on:
  workflow_run:
    workflows: ["Flag Service CI"]
    types: [completed]
  workflow_dispatch:
    inputs:
      image-tag:
        description: SHA da imagem já publicada no ECR
        required: true
        type: string
      environment:
        description: Ambiente do GitOps
        required: false
        default: prod
        type: choice
        options:
          - prod
          - staging

permissions:
  contents: read

jobs:
  promote:
    if: >-
      github.event_name == 'workflow_dispatch' || (
        github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'push' &&
        github.event.workflow_run.head_branch == 'main'
      )
    uses: fiap-tech-challenge-devops/reusable-workflows/.github/workflows/cd.yml@main
    with:
      service-name: flag-service
      image-repository: 762103020993.dkr.ecr.us-east-1.amazonaws.com/togglemaster/flag-service
      image-tag: ${{ github.event_name == 'workflow_dispatch' && inputs.image-tag || github.event.workflow_run.head_sha }}
      environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'prod' }}
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
